// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDwC95inedIfbVcLlcjTNSb2BlGiVR4Fk',
    appId: '1:577421801171:web:19c178438be712cd8e8626',
    messagingSenderId: '577421801171',
    projectId: 'kamgar-sahayak',
    authDomain: 'kamgar-sahayak.firebaseapp.com',
    storageBucket: 'kamgar-sahayak.firebasestorage.app',
    measurementId: 'G-3NEM20PGZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzYSA5BxM_9vAksweZA2VcXzzHjMD4Dxc',
    appId: '1:577421801171:android:a9385c61367987b88e8626',
    messagingSenderId: '577421801171',
    projectId: 'kamgar-sahayak',
    storageBucket: 'kamgar-sahayak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW99RkzFwAAziMCNJ2EuQMngUgcYuJAwk',
    appId: '1:577421801171:ios:e7ff8a89b46ab8498e8626',
    messagingSenderId: '577421801171',
    projectId: 'kamgar-sahayak',
    storageBucket: 'kamgar-sahayak.firebasestorage.app',
    androidClientId: '577421801171-iviqgbdj00oa3tcq96r1koehjadkbr9n.apps.googleusercontent.com',
    iosClientId: '577421801171-s0jbk605qi0p9b88s7blm754444hnn3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.kamgarSahayak',
  );
}
